version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-ia-project
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongodb:
    image: mongodb/mongodb-enterprise-server:7.0.4-ubi8
    container_name: mongodb-vector
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db
